In [3]:
import pandas as pd

# read CSV, arguments: filename, na_values, usecols = to select
# which columns in the file will be used
titanic = pd.read_csv('/Users/lara/repos/udacity_datascience_intro/titanic-data.csv',
                 na_values = ':')




titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
import numpy
import pandas
#import statsmodels.api as sm

def simple_heuristic():
    '''
    In this exercise, we will perform some rudimentary practices similar to those of
    an actual data scientist.
    
    Part of a data scientist's job is to use her or his intuition and insight to
    write algorithms and heuristics. A data scientist also creates mathematical models 
    to make predictions based on some attributes from the data that they are examining.

    We would like for you to take your knowledge and intuition about the Titanic
    and its passengers' attributes to predict whether or not the passengers survived
    or perished. You can read more about the Titanic and specifics about this dataset at:
    http://en.wikipedia.org/wiki/RMS_Titanic
    http://www.kaggle.com/c/titanic-gettingStarted
        
    In this exercise and the following ones, you are given a list of Titantic passengers
    and their associated information. More information about the data can be seen at the 
    link below:
    http://www.kaggle.com/c/titanic-gettingStarted/data. 

    For this exercise, you need to write a simple heuristic that will use
    the passengers' gender to predict if that person survived the Titanic disaster.
    
    You prediction should be 78% accurate or higher.
        
    Here's a simple heuristic to start off:
       1) If the passenger is female, your heuristic should assume that the
       passenger survived.
       2) If the passenger is male, you heuristic should
       assume that the passenger did not survive.
    
    You can access the gender of a passenger via passenger['Sex'].
    If the passenger is male, passenger['Sex'] will return a string "male".
    If the passenger is female, passenger['Sex'] will return a string "female".

    Write your prediction back into the "predictions" dictionary. The
    key of the dictionary should be the passenger's id (which can be accessed
    via passenger["PassengerId"]) and the associated value should be 1 if the
    passenger survied or 0 otherwise.

    For example, if a passenger is predicted to have survived:
    passenger_id = passenger['PassengerId']
    predictions[passenger_id] = 1

    And if a passenger is predicted to have perished in the disaster:
    passenger_id = passenger['PassengerId']
    predictions[passenger_id] = 0
    
    You can also look at the Titantic data that you will be working with
    at the link below:
    https://s3.amazonaws.com/content.udacity-data.com/courses/ud359/titanic_data.csv
    '''

    predictions = {}
    df = pandas.read_csv('/Users/lara/repos/udacity_datascience_intro/titanic-data.csv')
    for passenger_index, passenger in df.iterrows():
        passenger_id = passenger['PassengerId']

        # let's assume that if the passenger
        # is a male, then the passenger survived.
        if passenger['Sex'] == 'female':
            predictions[passenger_id] = 1
        else:
            predictions[passenger_id] = 0 

    return predictions

result = simple_heuristic()

result

{1: 1,
 2: 0,
 3: 0,
 4: 0,
 5: 1,
 6: 1,
 7: 1,
 8: 1,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 1,
 14: 1,
 15: 0,
 16: 0,
 17: 1,
 18: 1,
 19: 0,
 20: 0,
 21: 1,
 22: 1,
 23: 0,
 24: 1,
 25: 0,
 26: 0,
 27: 1,
 28: 1,
 29: 0,
 30: 1,
 31: 1,
 32: 0,
 33: 0,
 34: 1,
 35: 1,
 36: 1,
 37: 1,
 38: 1,
 39: 0,
 40: 0,
 41: 0,
 42: 0,
 43: 1,
 44: 0,
 45: 0,
 46: 1,
 47: 1,
 48: 0,
 49: 1,
 50: 0,
 51: 1,
 52: 1,
 53: 0,
 54: 0,
 55: 1,
 56: 1,
 57: 0,
 58: 1,
 59: 0,
 60: 1,
 61: 1,
 62: 0,
 63: 1,
 64: 1,
 65: 1,
 66: 1,
 67: 0,
 68: 1,
 69: 0,
 70: 1,
 71: 1,
 72: 0,
 73: 1,
 74: 1,
 75: 1,
 76: 1,
 77: 1,
 78: 1,
 79: 1,
 80: 0,
 81: 1,
 82: 1,
 83: 0,
 84: 1,
 85: 0,
 86: 0,
 87: 1,
 88: 1,
 89: 0,
 90: 1,
 91: 1,
 92: 1,
 93: 1,
 94: 1,
 95: 1,
 96: 1,
 97: 1,
 98: 1,
 99: 0,
 100: 1,
 101: 0,
 102: 1,
 103: 1,
 104: 1,
 105: 1,
 106: 1,
 107: 0,
 108: 1,
 109: 1,
 110: 0,
 111: 1,
 112: 0,
 113: 1,
 114: 0,
 115: 0,
 116: 1,
 117: 1,
 118: 1,
 119: 1,
 120: 0,
 121: 1,
 122: 1,
 123: 1,
 124: 0,
 125: 1,
 126: 1,
 127: 1,
 128: 1,
 129: 0,
 130: 1,
 131: 1,
 132: 1,
 133: 0,
 134: 0,
 135: 1,
 136: 1,
 137: 0,
 138: 1,
 139: 1,
 140: 1,
 141: 0,
 142: 0,
 143: 0,
 144: 1,
 145: 1,
 146: 1,
 147: 1,
 148: 0,
 149: 1,
 150: 1,
 151: 1,
 152: 0,
 153: 1,
 154: 1,
 155: 1,
 156: 1,
 157: 0,
 158: 1,
 159: 1,
 160: 1,
 161: 1,
 162: 0,
 163: 1,
 164: 1,
 165: 1,
 166: 1,
 167: 0,
 168: 0,
 169: 1,
 170: 1,
 171: 1,
 172: 1,
 173: 0,
 174: 1,
 175: 1,
 176: 1,
 177: 1,
 178: 0,
 179: 1,
 180: 1,
 181: 0,
 182: 1,
 183: 1,
 184: 1,
 185: 0,
 186: 1,
 187: 0,
 188: 1,
 189: 1,
 190: 1,
 191: 0,
 192: 1,
 193: 0,
 194: 1,
 195: 0,
 196: 0,
 197: 1,
 198: 1,
 199: 0,
 200: 0,
 201: 1,
 202: 1,
 203: 1,
 204: 1,
 205: 1,
 206: 0,
 207: 1,
 208: 1,
 209: 0,
 210: 1,
 211: 1,
 212: 0,
 213: 1,
 214: 1,
 215: 1,
 216: 0,
 217: 0,
 218: 1,
 219: 0,
 220: 1,
 221: 1,
 222: 1,
 223: 1,
 224: 1,
 225: 1,
 226: 1,
 227: 1,
 228: 1,
 229: 1,
 230: 0,
 231: 0,
 232: 1,
 233: 1,
 234: 0,
 235: 1,
 236: 0,
 237: 1,
 238: 0,
 239: 1,
 240: 1,
 241: 0,
 242: 0,
 243: 1,
 244: 1,
 245: 1,
 246: 1,
 247: 0,
 248: 0,
 249: 1,
 250: 1,
 251: 1,
 252: 0,
 253: 1,
 254: 1,
 255: 0,
 256: 0,
 257: 0,
 258: 0,
 259: 0,
 260: 0,
 261: 1,
 262: 1,
 263: 1,
 264: 1,
 265: 0,
 266: 1,
 267: 1,
 268: 1,
 269: 0,
 270: 0,
 271: 1,
 272: 1,
 273: 0,
 274: 1,
 275: 0,
 276: 0,
 277: 0,
 278: 1,
 279: 1,
 280: 0,
 281: 1,
 282: 1,
 283: 1,
 284: 1,
 285: 1,
 286: 1,
 287: 1,
 288: 1,
 289: 1,
 290: 0,
 291: 0,
 292: 0,
 293: 1,
 294: 0,
 295: 1,
 296: 1,
 297: 1,
 298: 0,
 299: 1,
 300: 0,
 301: 0,
 302: 1,
 303: 1,
 304: 0,
 305: 1,
 306: 1,
 307: 0,
 308: 0,
 309: 1,
 310: 0,
 311: 0,
 312: 0,
 313: 0,
 314: 1,
 315: 1,
 316: 0,
 317: 0,
 318: 1,
 319: 0,
 320: 0,
 321: 1,
 322: 1,
 323: 0,
 324: 0,
 325: 1,
 326: 0,
 327: 1,
 328: 0,
 329: 0,
 330: 0,
 331: 0,
 332: 1,
 333: 1,
 334: 1,
 335: 0,
 336: 1,
 337: 1,
 338: 0,
 339: 1,
 340: 1,
 341: 1,
 342: 0,
 343: 1,
 344: 1,
 345: 1,
 346: 0,
 347: 0,
 348: 0,
 349: 1,
 350: 1,
 351: 1,
 352: 1,
 353: 1,
 354: 1,
 355: 1,
 356: 1,
 357: 0,
 358: 0,
 359: 0,
 360: 0,
 361: 1,
 362: 1,
 363: 0,
 364: 1,
 365: 1,
 366: 1,
 367: 0,
 368: 0,
 369: 0,
 370: 0,
 371: 1,
 372: 1,
 373: 1,
 374: 1,
 375: 0,
 376: 0,
 377: 0,
 378: 1,
 379: 1,
 380: 1,
 381: 0,
 382: 0,
 383: 1,
 384: 0,
 385: 1,
 386: 1,
 387: 1,
 388: 0,
 389: 1,
 390: 0,
 391: 1,
 392: 1,
 393: 1,
 394: 0,
 395: 0,
 396: 1,
 397: 0,
 398: 1,
 399: 1,
 400: 0,
 401: 1,
 402: 1,
 403: 0,
 404: 1,
 405: 0,
 406: 1,
 407: 1,
 408: 1,
 409: 1,
 410: 0,
 411: 1,
 412: 1,
 413: 0,
 414: 1,
 415: 1,
 416: 0,
 417: 0,
 418: 0,
 419: 1,
 420: 0,
 421: 1,
 422: 1,
 423: 1,
 424: 0,
 425: 1,
 426: 1,
 427: 0,
 428: 0,
 429: 1,
 430: 1,
 431: 1,
 432: 0,
 433: 0,
 434: 1,
 435: 1,
 436: 0,
 437: 0,
 438: 0,
 439: 1,
 440: 1,
 441: 0,
 442: 1,
 443: 1,
 444: 0,
 445: 1,
 446: 1,
 447: 0,
 448: 1,
 449: 0,
 450: 1,
 451: 1,
 452: 1,
 453: 1,
 454: 1,
 455: 1,
 456: 1,
 457: 1,
 458: 0,
 459: 0,
 460: 1,
 461: 1,
 462: 1,
 463: 1,
 464: 1,
 465: 1,
 466: 1,
 467: 1,
 468: 1,
 469: 1,
 470: 0,
 471: 1,
 472: 1,
 473: 0,
 474: 0,
 475: 0,
 476: 1,
 477: 1,
 478: 1,
 479: 1,
 480: 0,
 481: 1,
 482: 1,
 483: 1,
 484: 0,
 485: 1,
 486: 0,
 487: 0,
 488: 1,
 489: 1,
 490: 1,
 491: 1,
 492: 1,
 493: 1,
 494: 1,
 495: 1,
 496: 1,
 497: 0,
 498: 1,
 499: 0,
 500: 1,
 501: 1,
 502: 0,
 503: 0,
 504: 0,
 505: 0,
 506: 1,
 507: 0,
 508: 1,
 509: 1,
 510: 1,
 511: 1,
 512: 1,
 513: 1,
 514: 0,
 515: 1,
 516: 1,
 517: 0,
 518: 1,
 519: 0,
 520: 1,
 521: 0,
 522: 1,
 523: 1,
 524: 0,
 525: 1,
 526: 1,
 527: 0,
 528: 1,
 529: 1,
 530: 1,
 531: 0,
 532: 1,
 533: 1,
 534: 0,
 535: 0,
 536: 0,
 537: 1,
 538: 0,
 539: 1,
 540: 0,
 541: 0,
 542: 0,
 543: 0,
 544: 1,
 545: 1,
 546: 1,
 547: 0,
 548: 1,
 549: 1,
 550: 1,
 551: 1,
 552: 1,
 553: 1,
 554: 1,
 555: 0,
 556: 1,
 557: 0,
 558: 1,
 559: 0,
 560: 0,
 561: 1,
 562: 1,
 563: 1,
 564: 1,
 565: 0,
 566: 1,
 567: 1,
 568: 0,
 569: 1,
 570: 1,
 571: 1,
 572: 0,
 573: 1,
 574: 0,
 575: 1,
 576: 1,
 577: 0,
 578: 0,
 579: 0,
 580: 1,
 581: 0,
 582: 0,
 583: 1,
 584: 1,
 585: 1,
 586: 0,
 587: 1,
 588: 1,
 589: 1,
 590: 1,
 591: 1,
 592: 0,
 593: 1,
 594: 0,
 595: 1,
 596: 1,
 597: 0,
 598: 1,
 599: 1,
 600: 1,
 601: 0,
 602: 1,
 603: 1,
 604: 1,
 605: 1,
 606: 1,
 607: 1,
 608: 1,
 609: 0,
 610: 0,
 611: 0,
 612: 1,
 613: 0,
 614: 1,
 615: 1,
 616: 0,
 617: 1,
 618: 0,
 619: 0,
 620: 1,
 621: 1,
 622: 1,
 623: 1,
 624: 1,
 625: 1,
 626: 1,
 627: 1,
 628: 0,
 629: 1,
 630: 1,
 631: 1,
 632: 1,
 633: 1,
 634: 1,
 635: 0,
 636: 0,
 637: 1,
 638: 1,
 639: 0,
 640: 1,
 641: 1,
 642: 0,
 643: 0,
 644: 1,
 645: 0,
 646: 1,
 647: 1,
 648: 1,
 649: 1,
 650: 0,
 651: 1,
 652: 0,
 653: 1,
 654: 0,
 655: 0,
 656: 1,
 657: 1,
 658: 0,
 659: 1,
 660: 1,
 661: 1,
 662: 1,
 663: 1,
 664: 1,
 665: 1,
 666: 1,
 667: 1,
 668: 1,
 669: 1,
 670: 0,
 671: 0,
 672: 1,
 673: 1,
 674: 1,
 675: 1,
 676: 1,
 677: 1,
 678: 0,
 679: 0,
 680: 1,
 681: 0,
 682: 1,
 683: 1,
 684: 1,
 685: 1,
 686: 1,
 687: 1,
 688: 1,
 689: 1,
 690: 0,
 691: 1,
 692: 0,
 693: 1,
 694: 1,
 695: 1,
 696: 1,
 697: 1,
 698: 0,
 699: 1,
 700: 1,
 701: 0,
 702: 1,
 703: 0,
 704: 1,
 705: 1,
 706: 1,
 707: 0,
 708: 1,
 709: 0,
 710: 1,
 711: 0,
 712: 1,
 713: 1,
 714: 1,
 715: 1,
 716: 1,
 717: 0,
 718: 0,
 719: 1,
 720: 1,
 721: 0,
 722: 1,
 723: 1,
 724: 1,
 725: 1,
 726: 1,
 727: 0,
 728: 0,
 729: 1,
 730: 0,
 731: 0,
 732: 1,
 733: 1,
 734: 1,
 735: 1,
 736: 1,
 737: 0,
 738: 1,
 739: 1,
 740: 1,
 741: 1,
 742: 1,
 743: 0,
 744: 1,
 745: 1,
 746: 1,
 747: 1,
 748: 0,
 749: 1,
 750: 1,
 751: 0,
 752: 1,
 753: 1,
 754: 1,
 755: 0,
 756: 1,
 757: 1,
 758: 1,
 759: 1,
 760: 0,
 761: 1,
 762: 1,
 763: 1,
 764: 0,
 765: 1,
 766: 0,
 767: 1,
 768: 0,
 769: 1,
 770: 1,
 771: 1,
 772: 1,
 773: 0,
 774: 1,
 775: 0,
 776: 1,
 777: 1,
 778: 0,
 779: 1,
 780: 0,
 781: 0,
 782: 0,
 783: 1,
 784: 1,
 785: 1,
 786: 1,
 787: 0,
 788: 1,
 789: 1,
 790: 1,
 791: 1,
 792: 1,
 793: 0,
 794: 1,
 795: 1,
 796: 1,
 797: 0,
 798: 0,
 799: 1,
 800: 0,
 801: 1,
 802: 0,
 803: 1,
 804: 1,
 805: 1,
 806: 1,
 807: 1,
 808: 0,
 809: 1,
 810: 0,
 811: 1,
 812: 1,
 813: 1,
 814: 0,
 815: 1,
 816: 1,
 817: 0,
 818: 1,
 819: 1,
 820: 1,
 821: 0,
 822: 1,
 823: 1,
 824: 0,
 825: 1,
 826: 1,
 827: 1,
 828: 1,
 829: 1,
 830: 0,
 831: 0,
 832: 1,
 833: 1,
 834: 1,
 835: 1,
 836: 0,
 837: 1,
 838: 1,
 839: 1,
 840: 1,
 841: 1,
 842: 1,
 843: 0,
 844: 1,
 845: 1,
 846: 1,
 847: 1,
 848: 1,
 849: 1,
 850: 0,
 851: 1,
 852: 1,
 853: 0,
 854: 0,
 855: 0,
 856: 0,
 857: 0,
 858: 1,
 859: 0,
 860: 1,
 861: 1,
 862: 1,
 863: 0,
 864: 0,
 865: 1,
 866: 0,
 867: 0,
 868: 1,
 869: 1,
 870: 1,
 871: 1,
 872: 0,
 873: 1,
 874: 1,
 875: 0,
 876: 0,
 877: 1,
 878: 1,
 879: 1,
 880: 0,
 881: 0,
 882: 1,
 883: 0,
 884: 1,
 885: 1,
 886: 0,
 887: 1,
 888: 0,
 889: 0,
 890: 1,
 891: 1}